import fs from 'node:fs';
import katex from 'katex';
const c=JSON.parse(fs.readFileSync(new URL('../public/course.json',import.meta.url),'utf8'));
const errors=[],warnings=[];const check=(ok,msg)=>{if(!ok)errors.push(msg);};
const expected=[7,7,8,7,8,7,7].flatMap((n,i)=>Array.from({length:n},(_,j)=>`${i+1}.${j+1}`)).concat(['F1','F2','F3','F4','F5','F6']);
const ids=c.lessons.map(l=>l.id);check(JSON.stringify(ids)===JSON.stringify(expected),'Lesson order or required lesson IDs differ from the course map.');
check(c.units.length===7,'Exactly seven main units required.');check(new Set(ids).size===ids.length,'Duplicate lesson IDs.');
function url(u,label){try{const x=new URL(u);check(x.protocol==='https:',`${label}: HTTPS required.`);check(!/example\.(com|org)|placeholder|coming[- ]?soon|youtube\.com\/results|youtu\.be\/$/i.test(u),`${label}: placeholder/search link.`);}catch{errors.push(label+': malformed URL.');}}
function video(v,label,bonus){for(const f of ['title','creator','url','videoId','purpose','lastVerified'])check(typeof v[f]==='string'&&v[f].trim(),`${label}: missing ${f}`);url(v.url,label);check(!/havrot|jensen/i.test(v.creator+' '+v.url),label+': excluded creator.');check(Number.isInteger(v.durationSeconds)&&v.durationSeconds>0,label+': invalid duration.');check(v.videoId===new URL(v.url).searchParams.get('v'),label+': URL/video ID mismatch.');check(v.verification?.page==='verified',label+': page verification missing.');if(v.segment){check(v.segment.start>=0&&v.segment.end<=v.durationSeconds&&v.segment.end>v.segment.start,label+': invalid segment.');check(!!v.segment.reason,label+': segment reason missing.');}const length=v.segment?v.segment.end-v.segment.start:v.durationSeconds;if(bonus)check(length<=720,label+': bonus exceeds 12 minutes.');if(v.verification.content!=='verified')warnings.push(label+': full video content review open.');}
function sheet(w,label){for(const f of ['title','source','sourceURL','url','answersURL','coverage','difficulty','lastVerified'])check(typeof w[f]==='string'&&w[f].trim(),`${label}: missing ${f}`);for(const f of ['sourceURL','url','answersURL'])url(w[f],label+' '+f);check(w.verification?.answerMatch==='verified',label+': matching answer verification missing.');}
let mathCount=0;
for(const l of c.lessons){check(l.goal&&l.notes.length>=1,l.id+': goal or notes missing.');check(l.learn.length>=2&&l.learn.length<=5,l.id+': requires 2–5 teaching videos.');check(l.bonus.length===2,l.id+': exactly two bonuses required.');check(l.worksheets.length>=1,l.id+': worksheet required.');check(new Set(l.bonus.map(v=>v.videoId)).size===2,l.id+': duplicated bonus source.');check(!l.bonus.some(v=>l.learn.some(x=>x.videoId===v.videoId)),l.id+': bonus repeats a teaching source.');check(c.units.some(u=>u.id===l.unit),l.id+': invalid unit.');if(l.financial)check(l.unit===7&&/^8\.[1-6]$/.test(l.nelson),l.id+': finance placement/cross-reference.');l.learn.forEach((v,i)=>video(v,`${l.id} Learn ${i+1}`,false));l.bonus.forEach((v,i)=>video(v,`${l.id} Bonus ${i+1}`,true));l.worksheets.forEach((w,i)=>sheet(w,`${l.id} Worksheet ${i+1}`));for(const text of [l.goal,...l.notes]){for(const match of text.matchAll(/\$([^$]+)\$/g)){try{katex.renderToString(match[1],{throwOnError:true,strict:'ignore'});mathCount++;}catch(e){errors.push(l.id+': invalid mathematics '+match[1]);}}}}
check(c.reviews.length===8,'Seven unit reviews and final review required.');for(const r of c.reviews){check(r.videos.length>=1&&r.worksheets.length>=1,r.title+': empty review.');r.videos.forEach((v,i)=>video(v,`${r.title} Video ${i+1}`,false));r.worksheets.forEach((w,i)=>sheet(w,`${r.title} Worksheet ${i+1}`));}
const allVideos=c.lessons.flatMap(l=>[...l.learn,...l.bonus]);const allSheets=c.lessons.flatMap(l=>l.worksheets);const report={checkedAt:new Date().toISOString(),structuralErrors:errors,openContentReviews:warnings.length,lessons:c.lessons.length,teachingVideoPlacements:c.lessons.reduce((n,l)=>n+l.learn.length,0),bonusVideoPlacements:c.lessons.reduce((n,l)=>n+l.bonus.length,0),uniqueLessonVideos:new Set(allVideos.map(v=>v.videoId)).size,worksheetPlacements:allSheets.length,uniqueLessonWorksheets:new Set(allSheets.map(w=>w.url)).size,reviewPages:c.reviews.length,mathExpressions:mathCount,releaseStatus:c.audit.releaseStatus};
fs.mkdirSync(new URL('../reports/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../reports/validation.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
if(process.argv.includes('--release')&&warnings.length){console.error('Release verification fails: full content reviews remain open.');process.exitCode=1;}
if(errors.length)process.exitCode=1;
