import 'katex/dist/katex.min.css';
import renderMathInElement from 'katex/contrib/auto-render';
import './style.css';

const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
let course;
let bookmarks=new Set();
try{bookmarks=new Set(JSON.parse(localStorage.getItem('open-functions-bookmarks')||'[]'));}catch{}
const lessonURL=id=>`#/lesson/${encodeURIComponent(id)}`;
const ext=(url,text,cls='button')=>`<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${text}<span class="sr-only"> (opens in a new tab)</span></a>`;
const format=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function maths(){renderMathInElement($('#main'),{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false,strict:'ignore'});}
function crumb(unit,title){return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="#/">Course</a>${unit?`<span>/</span><a href="#/unit/${unit.id}">Unit ${unit.id}</a>`:''}${title?`<span>/</span><span aria-current="page">${e(title)}</span>`:''}</nav>`;}
function lessonRow(l){return `<a class="lesson-row" href="${lessonURL(l.id)}"><span class="lesson-number">${l.financial?e(l.id):e(l.id)}</span><span><strong>${e(l.title)}</strong>${l.financial?`<small>Financial Applications · Nelson ${l.nelson}</small>`:''}</span><span class="row-meta">${l.learn.length} teaching · 2 worked examples</span><span class="row-icon" aria-hidden="true">↗</span></a>`;}
function drawNav(active){$('#course-nav').innerHTML=course.units.map(u=>`<details ${active===u.id?'open':''}><summary><span>${u.id}</span>${e(u.title)}</summary><a class="unit-overview" href="#/unit/${u.id}">Unit ${u.id} overview</a>${course.lessons.filter(l=>l.unit===u.id).map(l=>`<a href="${lessonURL(l.id)}" ${location.hash===lessonURL(l.id)?'aria-current="page"':''}>${e(l.id)} <span>${e(l.title)}</span></a>`).join('')}<a class="nav-review" href="#/review/${u.id}">Unit ${u.id} review</a></details>`).join('');}
function homepage(){
 return `${crumb()}<div class="eyebrow">GRADE 11 · UNIVERSITY PREPARATION</div><div class="home-title"><h1>Functions,<br>one lesson at a time.</h1><div class="course-code">MCR3U<span>7 units · 57 lessons</span></div></div><p class="lead">Visual explanations, worked problems and independent practice. Open the lesson you need, then choose the resources that help.</p><div class="intro-strip"><span><b>01</b> Learn it</span><span><b>02</b> Watch problems being solved</span><span><b>03</b> Try it yourself</span></div><p class="quiet">Worked examples are available before or after practice. Every resource is open to everyone.</p><div class="section-heading"><h2>The course</h2><a href="#/review/final">Final course review</a></div><div class="unit-list">${course.units.map(u=>`<a class="unit-row" href="#/unit/${u.id}"><span class="unit-no">0${u.id}</span><div><h3>${e(u.title)}</h3><p>${e(u.description)}</p></div><span class="unit-count">${course.lessons.filter(l=>l.unit===u.id&&!l.financial).length} lessons${u.id===7?'<small>+ 6 finance lessons</small>':''}</span><span class="row-icon" aria-hidden="true">↗</span></a>`).join('')}</div>${bookmarks.size?`<section class="saved"><h2>Your bookmarks</h2>${course.lessons.filter(l=>bookmarks.has(l.id)).map(lessonRow).join('')}<p class="quiet">Saved only in this browser.</p></section>`:''}<p class="audit-note"><strong>Content review is in progress.</strong> All lessons are populated; complete video-content checks remain open. <a href="#/sources">Read the resource audit</a> for verified details and unresolved checks.</p>`;
}
function unitpage(u){const ls=course.lessons.filter(l=>l.unit===u.id);return `${crumb(u,'Overview')}<div class="eyebrow">UNIT ${u.id}</div><h1>${e(u.title)}</h1><p class="lead">${e(u.description)}</p><div class="unit-tools"><span>${ls.length} lessons · videos &amp; worksheets</span><a class="button" href="#/review/${u.id}">Unit review</a></div><div class="lesson-list">${ls.filter(l=>!l.financial).map(lessonRow).join('')}</div>${u.id===7?`<section class="finance"><div class="eyebrow">WITHIN UNIT 7</div><h2>Financial Applications</h2><p>Six lessons connecting sequences and series to interest and ordinary simple annuities. F1–F6 correspond to Nelson 8.1–8.6.</p>${ls.filter(l=>l.financial).map(lessonRow).join('')}</section>`:''}<div class="review-callout"><h2>Bring the unit together</h2><p>Choose a review sheet or revisit a worked example. Use as much or as little as you need.</p><a class="button primary" href="#/review/${u.id}">Open unit review</a></div>`;}
function video(v,i,bonus=false){
 const segment=v.segment;
 const length=segment?`${format(segment.start)}–${format(segment.end)} · ${format(segment.end-segment.start)}`:format(v.durationSeconds);
 const url=segment?`${v.url}&t=${segment.start}s`:v.url;
 return `<article class="video-card"><div class="resource-index">${bonus?'WORKED EXAMPLE':'LEARN'} ${String(i+1).padStart(2,'0')}<span>${length}</span></div><h3>${e(v.topicLabel||v.title)}</h3>${v.topicLabel?`<p class="original-title">Original video title: ${e(v.title)}</p>`:''}<div class="creator">${e(v.creator)}</div><p>${e(v.purpose)}</p>${v.note?`<p class="resource-note">${e(v.note)}</p>`:''}${segment?`<div class="segment-note"><strong>Stop at ${format(segment.end)}.</strong> ${e(segment.reason)}</div>`:''}<div class="resource-actions">${ext(url,segment?'Watch segment':'Watch video','button primary')}<button class="button secondary embed-button" data-video="${e(v.videoId)}" data-start="${segment?.start||0}" data-end="${segment?.end||0}" data-title="${e(v.title)}">Play here</button></div><div class="embed-slot"></div></article>`;
}
function worksheet(w){return `<article class="worksheet-card"><div><span class="worksheet-label">${e(w.difficulty||'Core practice')}</span><h3>${e(w.title)}</h3><p>${e(w.coverage)}</p><p class="worksheet-source">${ext(w.sourceURL,e(w.source),'text-link')}${w.assignment?` · ${e(w.assignment)}`:''}</p>${w.answerNote?`<p class="resource-note">${e(w.answerNote)}</p>`:''}</div><div class="worksheet-actions">${ext(w.url,'Worksheet','button primary')}${ext(w.answersURL,'Answers / Solutions','button secondary')}</div></article>`;}
function lessonpage(l){const u=course.units.find(u=>u.id===l.unit),at=course.lessons.indexOf(l),prev=course.lessons[at-1],next=course.lessons[at+1];return `${crumb(u,`Lesson ${l.id}`)}<div class="lesson-title-line"><div class="eyebrow">${l.financial?'FINANCIAL APPLICATIONS':'LESSON'} ${e(l.id)} <span>· Nelson ${e(l.nelson)}</span></div><button class="bookmark" data-id="${l.id}" aria-pressed="${bookmarks.has(l.id)}">${bookmarks.has(l.id)?'Bookmarked':'Bookmark'}</button></div><h1>${e(l.title)}</h1><p class="lead goal">${e(l.goal)}</p><nav class="page-jumps" aria-label="Lesson resources"><a href="#learn" data-scroll="learn">Learn it <b>${l.learn.length}</b></a><a href="#bonus" data-scroll="bonus">Worked problems <b>${l.bonus.length}</b></a><a href="#practice" data-scroll="practice">Worksheets &amp; solutions</a><a href="#watch-for" data-scroll="watch-for">Watch for this</a></nav><section id="learn"><div class="section-heading"><h2>Learn it</h2><span>Foundations to application</span></div><div class="video-grid">${l.learn.map((v,i)=>video(v,i)).join('')}</div></section><section id="bonus"><div class="section-heading"><h2>Bonus: watch problems being solved</h2></div><p class="section-intro">Two worked examples. Watch before or after trying the worksheet.</p><div class="video-grid">${l.bonus.map((v,i)=>video(v,i,true)).join('')}</div></section><section id="practice"><div class="section-heading"><h2>Try it yourself</h2><span>Free external worksheets</span></div>${l.worksheets.map(worksheet).join('')}</section><section id="watch-for" class="watch-for"><h2>Watch for this</h2><ul>${l.notes.map(n=>`<li>${e(n)}</li>`).join('')}</ul></section><p class="resource-check">Resource pages checked ${course.lastUpdated}. <a href="#/sources">Verification scope and unresolved checks</a>.</p><nav class="lesson-pagination" aria-label="Other lessons">${prev?`<a href="${lessonURL(prev.id)}"><small>PREVIOUS LESSON</small>${prev.id} · ${e(prev.title)}</a>`:'<span></span>'}${next?`<a href="${lessonURL(next.id)}"><small>NEXT LESSON</small>${next.id} · ${e(next.title)}</a>`:`<a href="#/review/7">Unit 7 review</a>`}</nav>`;}
function reviewpage(id){const r=course.reviews.find(r=>String(r.id)===id),u=course.units.find(u=>String(u.id)===id);if(!r)return notfound();return `${crumb(u,r.title)}<div class="eyebrow">OPTIONAL REVIEW</div><h1>${e(r.title)}</h1><p class="lead">${e(r.description)}</p><section><h2>Review videos</h2><div class="video-grid">${r.videos.map((v,i)=>video(v,i)).join('')}</div></section><section><h2>Practice &amp; solutions</h2>${r.worksheets.map(worksheet).join('')}</section><div class="review-callout"><h2>Revisit a lesson</h2><p>Search a topic or jump to a lesson from the course navigation. Nothing needs to be submitted.</p><a href="${u?'#/unit/'+u.id:'#/'}" class="button">${u?'Back to unit':'Course home'}</a></div>`;}
function sources(){const a=course.audit||{};return `${crumb(null,'Sources & audit')}<div class="eyebrow">RESOURCE LIBRARY</div><h1>Sources &amp; verification</h1><p class="lead">This course organizes freely accessible resources from their original creators. Videos and worksheets remain on the providers’ websites.</p><section><h2>What was checked</h2><p>${e(a.summary||'Resource research is in progress.')}</p><div class="audit-stats"><div><strong>57</strong>lesson pages</div><div><strong>${a.uniqueVideos||0}</strong>video pages checked</div><div><strong>${a.uniqueWorksheets||0}</strong>worksheet files checked</div></div><p>Last resource check: <b>${course.lastUpdated}</b>. Links can change after that date. YouTube may show advertising on its own service.</p><p>Title, creator, runtime and public player availability checks do not certify that every explanation has been watched in full. The unresolved list below separates those checks.</p><a class="button" href="./resource-manifest.json" download>Download resource manifest</a></section><section><h2>Curriculum and numbering</h2><p>Seven units follow the course map. Unit 1 uses the requested school numbering; small cross-references identify the corresponding Nelson Functions 11 sections. Finance is part of Unit 7 and refers to Nelson Chapter 8.</p>${ext('https://www.edu.gov.on.ca/eng/curriculum/secondary/math1112currb.pdf','Ontario MCR3U expectations (pp. 43–54)','button')}<p>The textbook and supplied school documents are not reproduced here.</p></section><section><h2>Creators and sources</h2><ul>${(a.sources||[]).map(s=>`<li>${ext(s.url,e(s.name),'text-link')}</li>`).join('')}</ul><p>The site is independently written and is not affiliated with the Ontario Ministry of Education or the external resource providers.</p></section><section><h2>Unresolved verification</h2><p>${e(a.unresolvedSummary||'See the manifest for per-resource evidence.')}</p><ul class="unresolved-list">${(a.unresolved||[]).map(x=>`<li>${e(x)}</li>`).join('')}</ul></section>`;}
function notfound(){return '<h1>Page not found</h1><p>Choose a lesson from the course navigation.</p><a class="button" href="#/">Course home</a>';}
function render(){const parts=location.hash.replace(/^#\/?/,'').split('/'),type=parts[0],id=decodeURIComponent(parts[1]||'');let content,title='MCR3U course',unit;
 if(type==='unit'){unit=course.units.find(u=>String(u.id)===id);content=unit?unitpage(unit):notfound();title=unit?.title||'Page not found';}
 else if(type==='lesson'){const l=course.lessons.find(l=>l.id===id);unit=l&&course.units.find(u=>u.id===l.unit);content=l?lessonpage(l):notfound();title=l?`${l.id} ${l.title}`:'Page not found';}
 else if(type==='review'){content=reviewpage(id);title=id==='final'?'Course review':`Unit ${id} review`;unit=course.units.find(u=>String(u.id)===id);}
 else if(type==='sources'){content=sources();title='Sources & audit';}
 else if(!type) content=homepage();
 else {content=notfound();title='Page not found';}
 $('#main').innerHTML=content;document.title=`${title} · Open Functions`;drawNav(unit?.id);maths();$('#jump').value=type==='lesson'?id:'';$('#sidebar').classList.remove('mobile-open');$('#menu').setAttribute('aria-expanded','false');window.scrollTo(0,0);$('#main').focus({preventScroll:true});
}
function search(){const q=$('#search').value.trim().toLowerCase();if(!q){$('#search-results').innerHTML='';return;}const found=course.lessons.filter(l=>(`${l.id} ${l.financial?l.nelson:''} ${l.title} ${l.goal}`).toLowerCase().includes(q));$('#search-results').innerHTML=`<p>${found.length} ${found.length===1?'lesson':'lessons'} found</p>${found.map(l=>`<a href="${lessonURL(l.id)}">${e(l.id)} · ${e(l.title)}</a>`).join('')}`;}
document.addEventListener('click',ev=>{
 const skip=ev.target.closest('.skip');if(skip){ev.preventDefault();$('#main').focus();$('#main').scrollIntoView();return;}
 const currentLink=ev.target.closest('a[href^="#/"]');if(currentLink&&currentLink.hash===location.hash){ev.preventDefault();$('#sidebar').classList.remove('mobile-open');$('#menu').setAttribute('aria-expanded','false');$('#main').focus({preventScroll:true});window.scrollTo(0,0);return;}
 const jump=ev.target.closest('[data-scroll]');if(jump){ev.preventDefault();$('#'+jump.dataset.scroll)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return;}
 const b=ev.target.closest('.bookmark');if(b){const id=b.dataset.id;bookmarks.has(id)?bookmarks.delete(id):bookmarks.add(id);try{localStorage.setItem('open-functions-bookmarks',JSON.stringify([...bookmarks]));}catch{}b.textContent=bookmarks.has(id)?'Bookmarked':'Bookmark';b.setAttribute('aria-pressed',bookmarks.has(id));return;}
 const play=ev.target.closest('.embed-button');if(play){const slot=play.closest('article').querySelector('.embed-slot');if(slot.childElementCount){slot.innerHTML='';play.textContent='Play here';return;}const params=new URLSearchParams({autoplay:'1',rel:'0',start:play.dataset.start});if(+play.dataset.end)params.set('end',play.dataset.end);slot.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${e(play.dataset.video)}?${params}" title="${e(play.dataset.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><p class="quiet">If the player does not load, use Watch video to open the original page.</p>`;play.textContent='Close player';}
});
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('mobile-open');$('#menu').setAttribute('aria-expanded',open);});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&$('#sidebar').classList.contains('mobile-open')){$('#sidebar').classList.remove('mobile-open');$('#menu').setAttribute('aria-expanded','false');$('#menu').focus();}});
$('#search-form').addEventListener('submit',ev=>{ev.preventDefault();search();});$('#search').addEventListener('input',search);$('#jump').addEventListener('change',ev=>{if(ev.target.value)location.hash=lessonURL(ev.target.value);});window.addEventListener('hashchange',render);
fetch('./course.json').then(r=>{if(!r.ok)throw new Error('Course could not be loaded');return r.json();}).then(c=>{course=c;$('#jump').innerHTML+=[...c.lessons].map(l=>`<option value="${l.id}">${l.id} · ${e(l.title)}</option>`).join('');render();}).catch(()=>{$('#main').innerHTML='<h1>Unable to load the course</h1><p>Check your connection and reload this page.</p><button class="button" onclick="location.reload()">Reload</button>';});
